name: Fetch ChatGPT Invoice

on:
  schedule:
    # Runs at 12:00 UTC on the 26th of every month
    - cron: '0 12 26 * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  fetch-invoice:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: |
          python -m playwright install chromium
          
      - name: Run invoice fetcher
        env:
          OPENAI_EMAIL: ${{ secrets.OPENAI_EMAIL }}
          OPENAI_PASSWORD: ${{ secrets.OPENAI_PASSWORD }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python main.py
